# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  first-build:
    runs-on: ubuntu-latest

    steps:
    - name: graldew 파일 권한 확인1
      run: ls -l gradlew
      
    - name: graldew 파일 권한 수정1
      run: chmod 777 gradlew
      
    - name: graldew 파일 권한 확인1
      run: ls -l gradlew

  second-build:
    runs-on: ubuntu-latest
    needs: first-build

    steps:
    - name: graldew 파일 권한 확인2
      run: ls -l gradlew
